import Skills from "../components/Skills";
import About from "../components/About";
import Main from "../components/Main";
import Head from "next/head";
import Projects from "../components/Projects";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Logan Simpson | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link />
      </Head>

      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  );
}
